stage('Unit Test-Backend') {
    steps {
        script {
            withDockerContainer(image: 'snakee/golang-junit:1.21',
                                args: "-v ${env.WORKSPACE}:/workspace -w /workspace") {
                dir('bugtracker-backend') {
                    sh '''
                        export GOCACHE=/workspace/.cache/go-build
                        export GOMODCACHE=/workspace/.cache/go-mod
                        mkdir -p $GOCACHE $GOMODCACHE
                        go env
                        go test -v ./...
                    '''
                }
            }
        }
    }
}
